import { settingsHelpers } from '../consts'
import {
  CollisionCategory,
  HomeGoalieCollisionMask,
  FieldPlayerCollisionMask,
  AwayGoalieCollisionMask,
} from '../types/collision'

export type IPosition = 'goalie' | 'defLeft' | 'defRight' | 'center' | 'wingLeft' | 'wingRight'

export const positions = {
  home: {
    goalie: {
      startX: settingsHelpers.fieldWidthMid - 600,
      startY: settingsHelpers.fieldHeightMid,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.HomeGoalie,
      collisionMask: HomeGoalieCollisionMask,
    },
    center: {
      startX: settingsHelpers.fieldWidthMid - 200,
      startY: settingsHelpers.fieldHeightMid,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    wingLeft: {
      startX: settingsHelpers.fieldWidthMid - 100,
      startY: settingsHelpers.fieldHeightMid - 300,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    wingRight: {
      startX: settingsHelpers.fieldWidthMid - 100,
      startY: settingsHelpers.fieldHeightMid + 300,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    defLeft: {
      startX: settingsHelpers.fieldWidthMid - 400,
      startY: settingsHelpers.fieldHeightMid - 200,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    defRight: {
      startX: settingsHelpers.fieldWidthMid - 400,
      startY: settingsHelpers.fieldHeightMid + 200,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
  },
  away: {
    goalie: {
      startX: settingsHelpers.fieldWidthMid + 600,
      startY: settingsHelpers.fieldHeightMid,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.AwayGoalie,
      collisionMask: AwayGoalieCollisionMask,
    },
    center: {
      startX: settingsHelpers.fieldWidthMid + 200,
      startY: settingsHelpers.fieldHeightMid,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    wingLeft: {
      startX: settingsHelpers.fieldWidthMid + 100,
      startY: settingsHelpers.fieldHeightMid + 300,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    wingRight: {
      startX: settingsHelpers.fieldWidthMid + 100,
      startY: settingsHelpers.fieldHeightMid - 300,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    defLeft: {
      startX: settingsHelpers.fieldWidthMid + 400,
      startY: settingsHelpers.fieldHeightMid + 200,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    defRight: {
      startX: settingsHelpers.fieldWidthMid + 400,
      startY: settingsHelpers.fieldHeightMid - 200,
      defX: 0,
      defY: 0,
      offX: 0,
      offY: 0,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
  },
}
