import { settingsHelpers } from '../consts'
import {
  CollisionCategory,
  HomeGoalieCollisionMask,
  FieldPlayerCollisionMask,
  AwayGoalieCollisionMask,
} from '../types/collision'

export type IPosition = 'goalie' | 'defense' | 'wing' | 'center'

export const positions = {
  home: {
    goalie: {
      startX: settingsHelpers.fieldWidthMid - 600,
      startY: settingsHelpers.fieldHeightMid,
      startWithBallX: settingsHelpers.fieldWidthMid - 600,
      startWithBallY: settingsHelpers.fieldHeightMid,
      offenseX: settingsHelpers.fieldWidthMid - 600,
      offenseY: settingsHelpers.fieldHeightMid,
      defenseX: settingsHelpers.fieldWidthMid - 600,
      defenseY: settingsHelpers.fieldHeightMid,
      collisionCategory: CollisionCategory.HomeGoalie,
      collisionMask: HomeGoalieCollisionMask,
    },
    wing: {
      startX: settingsHelpers.fieldWidthMid - 150,
      startY: settingsHelpers.fieldHeightMid - 150,
      startWithBallX: settingsHelpers.fieldWidthMid - 100,
      startWithBallY: settingsHelpers.fieldHeightMid - 100,
      offenseX: settingsHelpers.fieldWidthMid + 400,
      offenseY: settingsHelpers.fieldHeightMid - 100,
      defenseX: settingsHelpers.fieldWidthMid - 150,
      defenseY: settingsHelpers.fieldHeightMid - 100,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    center: {
      startX: settingsHelpers.fieldWidthMid - 150,
      startY: settingsHelpers.fieldHeightMid + 150,
      startWithBallX: settingsHelpers.fieldWidthMid - 40,
      startWithBallY: settingsHelpers.fieldHeightMid,
      offenseX: settingsHelpers.fieldWidthMid + 400,
      offenseY: settingsHelpers.fieldHeightMid + 100,
      defenseX: settingsHelpers.fieldWidthMid - 150,
      defenseY: settingsHelpers.fieldHeightMid + 100,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    defense: {
      startX: settingsHelpers.fieldWidthMid - 400,
      startY: settingsHelpers.fieldHeightMid,
      startWithBallX: settingsHelpers.fieldWidthMid - 300,
      startWithBallY: settingsHelpers.fieldHeightMid,
      offenseX: settingsHelpers.fieldWidthMid + 50,
      offenseY: settingsHelpers.fieldHeightMid,
      defenseX: settingsHelpers.fieldWidthMid - 400,
      defenseY: settingsHelpers.fieldHeightMid,
      collisionCategory: CollisionCategory.HomeTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
  },
  away: {
    goalie: {
      startX: settingsHelpers.fieldWidthMid + 600,
      startY: settingsHelpers.fieldHeightMid,
      startWithBallX: settingsHelpers.fieldWidthMid + 600,
      startWithBallY: settingsHelpers.fieldHeightMid,
      offenseX: settingsHelpers.fieldWidthMid + 600,
      offenseY: settingsHelpers.fieldHeightMid,
      defenseX: settingsHelpers.fieldWidthMid + 600,
      defenseY: settingsHelpers.fieldHeightMid,
      collisionCategory: CollisionCategory.AwayGoalie,
      collisionMask: AwayGoalieCollisionMask,
    },
    wing: {
      startX: settingsHelpers.fieldWidthMid + 150,
      startY: settingsHelpers.fieldHeightMid + 150,
      startWithBallX: settingsHelpers.fieldWidthMid + 100,
      startWithBallY: settingsHelpers.fieldHeightMid + 100,
      offenseX: settingsHelpers.fieldWidthMid - 400,
      offenseY: settingsHelpers.fieldHeightMid + 100,
      defenseX: settingsHelpers.fieldWidthMid + 150,
      defenseY: settingsHelpers.fieldHeightMid + 100,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    center: {
      startX: settingsHelpers.fieldWidthMid + 150,
      startY: settingsHelpers.fieldHeightMid - 150,
      startWithBallX: settingsHelpers.fieldWidthMid + 40,
      startWithBallY: settingsHelpers.fieldHeightMid,
      offenseX: settingsHelpers.fieldWidthMid - 400,
      offenseY: settingsHelpers.fieldHeightMid - 100,
      defenseX: settingsHelpers.fieldWidthMid + 150,
      defenseY: settingsHelpers.fieldHeightMid - 100,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
    defense: {
      startX: settingsHelpers.fieldWidthMid + 400,
      startY: settingsHelpers.fieldHeightMid,
      startWithBallX: settingsHelpers.fieldWidthMid + 300,
      startWithBallY: settingsHelpers.fieldHeightMid,
      offenseX: settingsHelpers.fieldWidthMid - 50,
      offenseY: settingsHelpers.fieldHeightMid,
      defenseX: settingsHelpers.fieldWidthMid + 400,
      defenseY: settingsHelpers.fieldHeightMid,
      collisionCategory: CollisionCategory.AwayTeam,
      collisionMask: FieldPlayerCollisionMask,
    },
  },
}
